# Generated by Django 6.0.1 on 2026-05-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('nivel', models.CharField(choices=[('BASICO', 'Básico (Geralmente CPF)'), ('INTERMEDIÁRIO', 'Intermediário (Geralmente CNPJ)'), ('COMPLEXO', 'Complexo (Geralmente CNPJ)')], max_length=15, verbose_name='Nível de Complexidade')),
                ('status', models.CharField(choices=[('CADASTRADO', 'Cadastrado (Aguardando Sorteio)'), ('DISTRIBUIDO', 'Distribuido (Sorteado)'), ('CONFIRMADO', 'Aguardando Forasteiro (Conflito de Interesse)')], default='CADASTRADO', max_length=25, verbose_name='Status')),
                ('reaberto', models.BooleanField(default=False, verbose_name='É um caso reaberto?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('juiz_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Juiz Responsável')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
