# Generated by Django 6.0.4 on 2026-05-15 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Classe')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('orgao_competente', models.CharField(choices=[('PLENO', 'Tribunal Pleno (26)'), ('TURMAS', 'Turmas (14)'), ('PRESIDENCIA', 'Presidência (2)')], max_length=20, verbose_name='Órgão Competente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Classe Ativa/Vigente?')),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe Processual',
                'verbose_name_plural': 'Classe Processuais',
            },
        ),
        migrations.CreateModel(
            name='Magistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_processos', models.IntegerField(default=0, verbose_name='Conta de Distribuição')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=20, null=True)),
                ('parentes', models.ManyToManyField(blank=True, to='processos.magistrado', verbose_name='Parente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Sistema')),
            ],
            options={
                'verbose_name': 'Magistrado',
                'verbose_name_plural': 'Magistrados',
            },
        ),
        migrations.CreateModel(
            name='EstadoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('AFASTAMENTO', 'Afastamento > 30 dias'), ('FERIAS', 'Ferias'), ('LICENCA', 'Licença Médica'), ('APOSENTADORIA', '40 dias antes da aposentadoria')], max_length=30)),
                ('data_inicio', models.DateField(verbose_name='Início da Exclusão')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Exclusão (Se houver)')),
                ('magistrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.magistrado')),
            ],
            options={
                'verbose_name': 'Estado de exclusão',
                'verbose_name_plural': 'Estados de exclusão',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('status', models.CharField(choices=[('CADASTRADO', 'Cadastrado (Aguardando Distribuição)'), ('DISTRIBUIDO', 'Distribuído'), ('SUSPENSO', 'Suspenso / Excluído da Distribuição')], default='CADASTRADO', max_length=25)),
                ('data_autuacao', models.DateTimeField(auto_now_add=True)),
                ('classe_processual', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processos.classeprocessual', verbose_name='Classe Processual')),
                ('processo_prevento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo', verbose_name='Vinculado por Prevenção:')),
                ('relator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_relatados', to='processos.magistrado')),
            ],
            options={
                'verbose_name': 'Processo Judicial',
                'verbose_name_plural': 'Processos Judiciais',
            },
        ),
    ]
