# Generated by Django 6.0.4 on 2026-05-11 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='nivel',
            field=models.CharField(choices=[('BASICO', 'Básico (Geralmente CPF)'), ('INTERMEDIÁRIO', 'Intermediário (Geralmente CPF)'), ('COMPLEXO', 'Complexo (Geralmente CNPJ)')], max_length=15, verbose_name='Nível de Complexidade'),
        ),
        migrations.CreateModel(
            name='ConflitoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Justificativa de Conflito')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('juiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Juiz declarou Conflito')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processo', verbose_name='Processo com Conflito')),
            ],
            options={
                'verbose_name': 'Conflito de Interesse',
                'verbose_name_plural': 'Conflitos de Interesse',
            },
        ),
    ]
