# Generated by Django 6.0.4 on 2026-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Distribuição')),
                ('processo_numero', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('classe_sigla', models.CharField(max_length=20, verbose_name='Classe')),
                ('magistrado_sorteado', models.CharField(max_length=150, verbose_name='Magistrado Relator')),
                ('tipo_distribuicao', models.CharField(max_length=50, verbose_name='Tipo de Distribuição')),
                ('fundamento_legal', models.TextField(verbose_name='Fundamento Regimental/Legal')),
            ],
            options={
                'verbose_name': 'Ata de Distribuição',
                'verbose_name_plural': 'Atas de Distribuição',
            },
        ),
        migrations.AlterModelOptions(
            name='classeprocessual',
            options={'verbose_name': 'Classe Processual', 'verbose_name_plural': 'Classes Processuais'},
        ),
        migrations.AlterField(
            model_name='estadoexclusao',
            name='motivo',
            field=models.CharField(choices=[('AFASTAMENTO', 'Afastamento > 30 dias'), ('APOSENTADORIA', '40 dias antes da aposentadoria'), ('FERIAS', 'Ferias'), ('LICENCA', 'Licença Médica')], max_length=30),
        ),
    ]
